services:
  portfolio:
    build: .
    image: ghcr.io/jfxg/portfolio:latest
    ports:
      - "3500:3000"
    environment:
      PORT: 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`john.gaquin.dev`)"
      - "traefik.http.routers.portfolio.entrypoints=https"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
